version: '3.9'
services:
  app-nebula-swagger: 
    restart: on-failure
    build: 
      context: .
      dockerfile: .docker/app/Dockerfile
    ports:
      - 9000:9000
  app-nebula-nginx:
    restart: on-failure
    ports:
      - 8080:80
    volumes:
      - ./.docker/nginx/conf.d/staging/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/logs:/var/log/nginx
    depends_on:
      - app-nebula-swagger