version: '3.9'
services:
  app-nebula-nginx:
    image: nginx:latest
    container_name: nebula-api-docs-nginx
    ports:
      - 8080:80
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./.docker/nginx/conf.d/dev/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx