(async () => {
  console.table(require('dotenv').config().parsed);
  const express = require('express');
  const swaggerUI = require('swagger-ui-express');
  const { AppConfig } = require('./const');
  const app = express();
  
  // config trust proxy
  app.enable('trust proxy');
  
  // load swagger yml
  // solution generated by Bing AI
  const fs = require('fs');
  const jsYaml = require('js-yaml');
  const RefParser = require('json-schema-ref-parser');
  
  const apiSpec = await RefParser.dereference(
    jsYaml.load(fs.readFileSync('./swagger.yml', 'utf8')),
    {
      resolve: {
        file: {
          order: 1,
          read(file) {
            return fs.readFileSync(file.url, 'utf8');
          },
        },
      },
    }
  );
  
  // find the env in yml config and replace with environment variable values.
  // the regex was generated by Bing AI :)
  const specsWithEnvReplacement = JSON.stringify(apiSpec).replace(/\$\{([A-Z_]+)\}/g, (match, word) => AppConfig[word]);
  
  // register swagger
  app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(JSON.parse(specsWithEnvReplacement), {
    customCssUrl: 'https://cdn.jsdelivr.net/npm/swagger-ui-themes@3.0.0/themes/3.x/theme-material.css',
    customSiteTitle: 'Nebula API Docs'
  }));
  
  app.use(express.urlencoded({ extended: true }));
  app.use(express.json());
  
  app.listen(AppConfig.PORT, AppConfig.HOST, () => {
    console.log('Nebula docs server started');
  });
})();